# RENAME FILE TO 'config.yml'
bot:
  token: ADJFASJDNFPUIQHEPRFUHWERU9FH...
  owner_ids:
    - 767346288882221077
    - 767346288882221077
  prefix: $
  default_bet: 100
  bonus_multiplier: 5 # bonus = default_bet * multiplier
  bonus_cooldown: 12 # Bonus every x hours
  cd discord
  python bot.py
