# RENAME FILE TO 'config.yml'
bot:
  token: MTA2NzEzNTM3Mzk4NzMwMzU2NQ.G4ZLGu.GkU2HWlPXBJL-NhoVWxJZEhc7lEdwSBcCFfSXs...
  owner_ids:
    - 700733644729483384
    - 700733644729483384
  prefix: $
  default_bet: 100
  bonus_multiplier: 5 # bonus = default_bet * multiplier
  bonus_cooldown: 12 # Bonus every x hours
